namespace: vecraft-system
image:
  repository: ghcr.io/ynyeh0221/vecraft
  tag: main
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
    ephemeral-storage: "1Gi"
  limits:
    cpu: "500m"
    memory: "256Mi"
    ephemeral-storage: "2Gi"