apiVersion: apps/v1
kind: Deployment
metadata:
  name: vecraft-operator
  namespace: {{ .Values.namespace }}
  labels:
    app: vecraft-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vecraft-operator
  template:
    metadata:
      labels:
        app: vecraft-operator
    spec:
      serviceAccountName: vecraft-operator
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - kopf
            - run
            - /operator/operator.py
            - --verbose
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
              ephemeral-storage: {{ index .Values.resources.requests "ephemeral-storage" }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
              ephemeral-storage: {{ index .Values.resources.limits "ephemeral-storage" }}
          volumeMounts:
            - name: operator-script
              mountPath: /operator
      volumes:
        - name: operator-script
          configMap:
            name: vecraft-operator-script