apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vecraft-operator
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: vecraft-operator
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: vecraft-operator
  apiGroup: rbac.authorization.k8s.io