apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vecraftdatabases.vecraft.io
spec:
  group: vecraft.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                root:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
              required:
                - root
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: vecraftdatabases
    singular: vecraftdatabase
    kind: VecraftDatabase
    shortNames:
      - vdb