apiVersion: apps/v1
kind: Deployment
metadata:
  name: vecraft-operator
  namespace: vecraft-system
  labels:
    app: vecraft-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vecraft-operator
  template:
    metadata:
      labels:
        app: vecraft-operator
    spec:
      serviceAccountName: vecraft-operator
      containers:
        - name: operator
          image: ghcr.io/ynyeh0221/vecraft:main
          command:
            - "kopf"
            - "run"
            - "/operator/operator.py"
            - "--verbose"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "500m"
              memory: "256Mi"
              ephemeral-storage: "2Gi"
          volumeMounts:
            - name: operator-script
              mountPath: /operator
      volumes:
        - name: operator-script
          configMap:
            name: vecraft-operator-script