apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vecraft-operator
  namespace: vecraft-system
subjects:
  - kind: ServiceAccount
    name: vecraft-operator
    namespace: vecraft-system
roleRef:
  kind: Role
  name: vecraft-operator
  apiGroup: rbac.authorization.k8s.io