apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vecraft-operator
  namespace: vecraft-system
rules:
  # Manage VecraftDatabase CR and status
  - apiGroups: ["vecraft.io"]
    resources: ["vecraftdatabases", "vecraftdatabases/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Manage StatefulSet
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Manage Service and Pod
  - apiGroups: ["",]
    resources: ["services", "pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]