name: Test, Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          # Install the package in development mode
          pip install -e .
          # Install test dependencies
          pip install pytest pytest-timeout
          # Ensure hnswlib is properly built
          pip install --force-reinstall --no-deps hnswlib

      - name: Run unit tests
        timeout-minutes: 15
        run: |
          source .venv/bin/activate
          pytest tests -v --timeout=60

      - name: Login with PAT
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Create Dockerfile
        run: |
          cat > Dockerfile << 'EOF'
          FROM python:3.11-slim

          WORKDIR /app

          # Install required system dependencies
          RUN apt-get update && apt-get install -y --no-install-recommends \
              build-essential \
              && apt-get clean \
              && rm -rf /var/lib/apt/lists/*

          # Copy your project files
          COPY . /app/

          # Fix for src layout packages - install in a way that makes imports work
          RUN pip install --no-cache-dir .
          
          # Create a simple wrapper script that fixes the import issue
          RUN echo '#!/usr/bin/env python3' > /usr/local/bin/vecraft && \
              echo 'from vecraft.cli import entry_point' >> /usr/local/bin/vecraft && \
              echo 'entry_point()' >> /usr/local/bin/vecraft && \
              chmod +x /usr/local/bin/vecraft

          # Create a volume for data persistence
          VOLUME /data

          # Set the working directory to /data by default
          WORKDIR /data

          # Set environment variable for data location
          ENV VCRAFT_ROOT=/data

          # Default command: show help
          ENTRYPOINT ["vecraft"]
          CMD ["--help"]
          EOF

      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/${{ github.repository }}:latest
          docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Verify Docker image
        run: |
          # Test that the CLI is accessible in the image
          docker run --rm ghcr.io/${{ github.repository }}:latest --help

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}