name: Test, Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          # Install the package in development mode
          pip install -e .
          # Install test dependencies
          pip install pytest pytest-timeout
          # Ensure hnswlib is properly built
          pip install --force-reinstall --no-deps hnswlib

      - name: Run unit tests
        timeout-minutes: 15
        run: |
          source .venv/bin/activate
          pytest tests -v --timeout=60

      - name: Login with PAT
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Create Dockerfile
        run: |
          # First, check your pyproject.toml configuration
          cat pyproject.toml
          
          cat > Dockerfile << 'EOF'
          FROM python:3.11-slim

          WORKDIR /app

          # Install required system dependencies
          RUN apt-get update && apt-get install -y --no-install-recommends \
              build-essential \
              && apt-get clean \
              && rm -rf /var/lib/apt/lists/*

          # Copy your project files
          COPY . /app/

          # Install your package in standard mode
          RUN pip install --no-cache-dir .
          
          # Create a volume for data persistence
          VOLUME /data

          # Set the working directory to /data by default
          WORKDIR /data

          # Set environment variable for data location
          ENV VCRAFT_ROOT=/data

          # Default command: show help
          # Use explicitly the full path to the installed script 
          ENTRYPOINT ["/usr/local/bin/vecraft"]
          CMD ["--help"]
          EOF

      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/${{ github.repository }}:latest
          docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Verify Docker image
        run: |
          # Test that the CLI is accessible in the image
          docker run --rm ghcr.io/${{ github.repository }}:latest --help

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}